# CI Pipeline - Build and Test
# Runs on every push and pull request to validate code quality

trigger:
  branches:
    include:
      - main
      - master
      - develop
  paths:
    exclude:
      - '*.md'
      - 'docs/**'

pr:
  branches:
    include:
      - main
      - master
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js $(NODE_VERSION)'
            inputs:
              versionSpec: '$(NODE_VERSION)'

          # - task: Cache@2
          #   displayName: 'Cache npm dependencies'
          #   inputs:
          #     key: 'npm | "$(Agent.OS)" | package-lock.json'
          #     restoreKeys: |
          #       npm | "$(Agent.OS)"
          #     path: $(npm_config_cache)
          #   continueOnError: true

          - script: npm ci
            displayName: 'Install dependencies'

          - script: npm run typecheck
            displayName: 'TypeScript type checking'

          - script: npm run lint
            displayName: 'Lint code'
            continueOnError: true

          - script: npm test -- --run
            displayName: 'Run tests'
            env:
              NODE_ENV: test

          - script: npm run build
            displayName: 'Build application'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish build artifacts'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/build'
              artifact: 'build'
              publishLocation: 'pipeline'
            condition: succeeded()

          - task: PublishPipelineArtifact@1
            displayName: 'Publish server artifacts'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/dist'
              artifact: 'dist'
              publishLocation: 'pipeline'
            condition: succeeded()

  - stage: E2E
    displayName: 'E2E Tests'
    dependsOn: Build
    jobs:
      - job: PlaywrightTests
        displayName: 'Playwright E2E Tests'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js $(NODE_VERSION)'
            inputs:
              versionSpec: '$(NODE_VERSION)'

          - script: npm ci
            displayName: 'Install dependencies'

          - script: npx playwright install --with-deps chromium
            displayName: 'Install Playwright browsers'

          - script: npm run test:e2e
            displayName: 'Run Playwright E2E tests'
            env:
              CI: true
              NODE_ENV: test

          - task: PublishTestResults@2
            displayName: 'Publish E2E test results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'test-results/e2e-results.xml'
              testRunTitle: 'Playwright E2E Tests'
            condition: always()

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Playwright report'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/playwright-report'
              artifact: 'playwright-report'
              publishLocation: 'pipeline'
            condition: always()
