# CI Pipeline - Build and Test
# Runs on every push and pull request to validate code quality

trigger:
  branches:
    include:
      - main
      - master
      - develop
  paths:
    exclude:
      - '*.md'
      - 'docs/**'

pr:
  branches:
    include:
      - main
      - master
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js $(NODE_VERSION)'
            inputs:
              versionSpec: '$(NODE_VERSION)'

          # - task: Cache@2
          #   displayName: 'Cache npm dependencies'
          #   inputs:
          #     key: 'npm | "$(Agent.OS)" | package-lock.json'
          #     restoreKeys: |
          #       npm | "$(Agent.OS)"
          #     path: $(npm_config_cache)
          #   continueOnError: true

          - script: npm ci
            displayName: 'Install dependencies'

          - script: npm run typecheck
            displayName: 'TypeScript type checking'

          - script: npm run lint
            displayName: 'Lint code'
            continueOnError: true

          - script: npm test -- --run
            displayName: 'Run tests'
            env:
              NODE_ENV: test

          - script: npm run build
            displayName: 'Build application'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish build artifacts'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/build'
              artifact: 'build'
              publishLocation: 'pipeline'
            condition: succeeded()

          - task: PublishPipelineArtifact@1
            displayName: 'Publish server artifacts'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/dist'
              artifact: 'dist'
              publishLocation: 'pipeline'
            condition: succeeded()

  - stage: BumpVersion
    displayName: 'Bump Version'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: BumpVersion
        displayName: 'Bump Patch Version'
        steps:
          - checkout: self
            persistCredentials: true

          - task: NodeTool@0
            displayName: 'Install Node.js $(NODE_VERSION)'
            inputs:
              versionSpec: '$(NODE_VERSION)'

          - script: |
              git config user.email "azure-pipelines@dev.azure.com"
              git config user.name "Azure Pipelines"
            displayName: 'Configure Git'

          - script: node scripts/bump-version.js patch
            displayName: 'Bump patch version'

          - script: |
              NEW_VERSION=$(node -p "require('./package.json').version")
              git add package.json
              git commit -m "chore: bump version to ${NEW_VERSION} [skip ci]"
              git push origin HEAD:main
            displayName: 'Commit and push version bump'
