# Docker Build Pipeline - Build and Push to Azure Container Registry
# Builds the Docker image and pushes it to a configurable Azure Container Registry

trigger:
  branches:
    include:
      - main
      - master
  tags:
    include:
      - 'v*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Container Registry variables - set these in your pipeline or variable group
  # ACR_REGISTRY: 'yourregistry.azurecr.io'
  # ACR_USERNAME: 'your-acr-username'
  # ACR_PASSWORD: 'your-acr-password' (should be a secret variable)

  # Default values (override in pipeline variables)
  - name: IMAGE_NAME
    value: 'qr-hunt'
  - name: DOCKERFILE_PATH
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: BUILD_CONTEXT
    value: '$(Build.SourcesDirectory)'
  - name: NODE_VERSION
    value: '22.x'

stages:
  - stage: BumpVersion
    displayName: 'Bump Version'
    jobs:
      - job: BumpVersion
        displayName: 'Bump Patch Version'
        steps:
          - checkout: self
            persistCredentials: true

          - task: NodeTool@0
            displayName: 'Install Node.js $(NODE_VERSION)'
            inputs:
              versionSpec: '$(NODE_VERSION)'

          - script: |
              git config user.email "azure-pipelines@dev.azure.com"
              git config user.name "Azure Pipelines"
            displayName: 'Configure Git'

          - script: node scripts/bump-version.js patch
            displayName: 'Bump patch version'

          - script: |
              NEW_VERSION=$(node -p "require('./package.json').version")
              echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$NEW_VERSION"
              git add package.json
              git commit -m "chore: bump version to ${NEW_VERSION} [skip ci]"
              git push origin HEAD:main
            displayName: 'Commit and push version bump'
            name: version

  - stage: Build
    displayName: 'Build Docker Image'
    dependsOn: BumpVersion
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push Docker Image'
        variables:
          APP_VERSION: $[ stageDependencies.BumpVersion.BumpVersion.outputs['version.APP_VERSION'] ]
        steps:
          - checkout: self

          - script: |
              git pull origin main
            displayName: 'Pull latest version'

          - script: |
              docker build \
                -f $(DOCKERFILE_PATH) \
                -t $(ACR_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId) \
                -t $(ACR_REGISTRY)/$(IMAGE_NAME):$(APP_VERSION) \
                -t $(ACR_REGISTRY)/$(IMAGE_NAME):latest \
                --build-arg BUILD_ID=$(Build.BuildId) \
                $(BUILD_CONTEXT)
            displayName: 'Build Docker image'

          - script: |
              docker login $(ACR_REGISTRY) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
            displayName: 'Login to Azure Container Registry'

          - script: |
              docker push $(ACR_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId)
              docker push $(ACR_REGISTRY)/$(IMAGE_NAME):$(APP_VERSION)
              docker push $(ACR_REGISTRY)/$(IMAGE_NAME):latest
            displayName: 'Push image to ACR'

          - script: |
              docker logout $(ACR_REGISTRY)
            displayName: 'Logout from ACR'
            condition: always()

  - stage: Scan
    displayName: 'Security Scan'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: SecurityScan
        displayName: 'Container Security Scan'
        steps:
          - script: |
              docker login $(ACR_REGISTRY) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
            displayName: 'Login to Azure Container Registry'

          - script: |
              docker pull $(ACR_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId)
            displayName: 'Pull built image'

          # Optional: Add container scanning tool like Trivy
          - script: |
              docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
                aquasec/trivy:latest image \
                --exit-code 0 \
                --severity HIGH,CRITICAL \
                --no-progress \
                $(ACR_REGISTRY)/$(IMAGE_NAME):$(Build.BuildId)
            displayName: 'Scan image with Trivy'
            continueOnError: true

          - script: |
              docker logout $(ACR_REGISTRY)
            displayName: 'Logout from ACR'
            condition: always()
